# Generated by Django 3.0.7 on 2020-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='성함')),
                ('phone', models.CharField(max_length=30, verbose_name='연락처')),
                ('address', models.TextField(verbose_name='주소')),
                ('preferTime', models.TextField(verbose_name='선호시간')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
